// Registers what's in content/ so the static build can import it.
//
//   content/labs/<slug>/Demo.tsx  →  src/generated/labs.ts
//
// The site reads frontmatter with the file system at build time, but a demo is
// code: it has to be imported, and imports are static. This script writes the
// import table — one lazy import per lab, so a demo's JavaScript only loads
// when someone opens it. It runs before `dev`, `build` and `check`; the output
// is committed so lint and typecheck work on a fresh clone.
//
// Adding a lab: create the folder with lab.mdx and Demo.tsx. That's it.

import { existsSync } from "node:fs";
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const root = process.cwd();
const labsDir = path.join(root, "content", "labs");
const outFile = path.join(root, "src", "generated", "labs.ts");

const dirs = existsSync(labsDir)
  ? (await readdir(labsDir, { withFileTypes: true }))
      .filter((d) => d.isDirectory() && !d.name.startsWith("."))
      .map((d) => d.name)
      .sort()
  : [];

const problems = [];
for (const slug of dirs) {
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)) {
    problems.push(`${slug}: folder name must be a slug (a-z, 0-9, dashes)`);
  }
  if (!existsSync(path.join(labsDir, slug, "lab.mdx"))) {
    problems.push(`${slug}: missing lab.mdx`);
  }
  if (!existsSync(path.join(labsDir, slug, "Demo.tsx"))) {
    problems.push(`${slug}: missing Demo.tsx`);
  }
}
if (problems.length) {
  console.error("[content] labs are incomplete:\n  " + problems.join("\n  "));
  process.exit(1);
}

const lines = [
  "// Generated by scripts/gen-content.mjs — do not edit. Run `npm run gen`.",
  'import type { ComponentType } from "react";',
  "",
  "/** Lab slug → lazy import of its Demo component. */",
  "export const labDemos: Record<",
  "  string,",
  "  () => Promise<{ default: ComponentType }>",
  "> = {",
  ...dirs.map(
    (slug) => `  "${slug}": () => import("../../content/labs/${slug}/Demo"),`,
  ),
  "};",
  "",
  "export const labSlugs = Object.keys(labDemos);",
  "",
];
const next = lines.join("\n");

await mkdir(path.dirname(outFile), { recursive: true });
const current = existsSync(outFile) ? await readFile(outFile, "utf-8") : "";
if (current !== next) {
  await writeFile(outFile, next);
  console.log(
    `[content] ${dirs.length} lab(s) registered → src/generated/labs.ts`,
  );
}
